### PR TITLE
tilt: speed up compiling of binaries

### PR DESCRIPTION
**Pull request by akselleirv**
Closes https://github.com/flux-iac/tofu-controller/issues/1225

### CODE REVIEW

**Comment by chanwit** [comment]
@akselleirv thank you for the PR
please ping us when it is ready to review

**Comment by akselleirv** [comment]
@chanwit it’s ready for review. I’ll keep it as a draft when it is not ready!

**Comment by chanwit** [comment]
got it! thank you @akselleirv 
I'm reviewing it now.

**Review by chanwit — APPROVED** [review]
LGTM

Thank you @akselleirv :1st_place_medal: !!

**Pull request merged**
