### PR TITLE
branch planner is now checking for both PostPlanningWebhookFailedReason and TFExecInitFailedReason for failing PR

### LINKED ISSUE #1270: Branch planner does not comment of PR if plan failed due to post plan web hook
If post plan web hook is configured and plan failed because of it the Branch Planner does not post a comment on the PR. 

possibly here is the reason:
https://github.com/flux-iac/tofu-controller/blob/786da834e38521155af4d2ea34e285cd63ff24e3/internal/informer/branch-planner/informer.go#L152

### PR DESCRIPTION
**Pull request by raz-bn**
fixes #1270

### CODE REVIEW

**Comment by chanwit** [comment]
Thank you @raz-bn 
We got many unrelated red in the CI. I'm taking a look at it.

**Comment by chanwit** [comment]
Will resolve this issue first to make the CI green: https://github.com/flux-iac/tofu-controller/issues/1269

**Comment by ilithanos** [comment]
@raz-bn could I get you to pull on the latest changes from our main, as that should fix the CI

**Comment by raz-bn** [comment]
@ilithanos hey, I updated the branch :)

**Review by yitsushi — APPROVED** [review]

**Pull request merged**
