### PR TITLE
add private registries integration docs

### PR DESCRIPTION
**Pull request by ArieLevs**
fixes: #1189

### CODE REVIEW

**Comment by ArieLevs** [comment]
@ilithanos done

**Review by ilithanos — CHANGES_REQUESTED** [review]
Thanks a lot for getting the link from index.md into the PR.

You've written a good piece of documentation and I really appreciate you taking the time to help out.

There's a few corrections needed to increase the readability of the documentation suggested in the review, when these sections are updated I can merge the PR 👍

**Comment by ArieLevs** [comment]
I knew I should let chatGPT do the grammer :sweat_smile: done, committed via the PR

**Review by ilithanos — APPROVED** [review]
Haha :) LGTM 🥇 thanks again for the contribution

**Pull request merged**
