### PR TITLE
Helm chart url fixes

### PR DESCRIPTION
**Pull request by ilithanos**
This pr contains several updates to the helm chart:

- update image registry values to the new flux-iac organization
- update documentation metadata in chart to flux-iac pages
- update readme for the helm chart to contain these changes.

I havn't changed the chart version even though i think that would be the way to go. But since charts are currently linked to the controller versions i'll leave that up to the maintainers.

This solves the helm chart part of #1200

### CODE REVIEW

**Comment by ilithanos** [comment]
hmm seems like i managed to generate the documentation with a newer version of helm-docs. Want me to generate it with the older version?

**Comment by chanwit** [comment]
Please update the pipeline as you see fit.

**Comment by ilithanos** [comment]
There we go ;) updated the makefile to use the newer version of helm-docs.

**Review by chanwit — APPROVED** [review]
LGTM

Thank you so much @ilithanos

**Pull request merged**
