### PR TITLE
Helm chart rename

### LINKED ISSUE #1268: tfVarsFiles is missing in helm chart crds
Hi,

I was trying to use tfVarsFiles feature using helm chart 0.16.0-rc.4, during flux reconcile I get error that tfVarsFiles is missing in schema. I further investigate the issue and find out that tfVarsFiles crd specification:
https://github.com/flux-iac/tofu-controller/blob/main/config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml#L9815

is missing in helm chart crd (and also the version in this file is not set to latest 0.16.0-rc.4):
https://github.com/flux-iac/tofu-controller/blob/main/charts/tf-controller/crds/crds.yaml

### PR DESCRIPTION
**Pull request by ilithanos**
#1252 has no comments on this.

This should rename the helm chart to the new tofu-controller naming and ensure versions in values and labels are tagged with the rc.4 version of the tofu controller.

It should also change the CI to use the new naming convention for both chart and controller

Also fixes #1268 by updating the CRDs within the chart

### CODE REVIEW

**Comment by ilithanos** [comment]
Not fully ready for review yet. Will add reviewers when all tests etc are working.

**Comment by ilithanos** [comment]
Hmm interesting that this change breaks all the tests with a go version syntax error. I'll look into what is going on.

**Comment by ilithanos** [comment]
The tests starting to fail wasn't related to this specific branch, but would happen in all branches:

https://github.com/kubernetes-sigs/controller-runtime/issues/2720

Using the latest tag for pulling in versions in CI pipelines are in general bad practise. I've pinned the version of setup-envtest to solve the issue for now. 

Will create a seperate issue for this topic instead of going into to much detail here.

**Comment by ilithanos** [comment]
While renaming the chart i also updated the CRDs with the changes from config/crd/bases which should fix #1268

**Comment by ilithanos** [comment]
This should be ready for review, but i might have missed something that could have side effects without knowing. 

Especially when it comes to the CRDs. So any feedback would be appreciated.

**Review by chanwit — APPROVED** [review]
LGTM

Thank you @ilithanos :1st_place_medal:

**Pull request merged**
